### ISSUE TITLE
Decrease overhead

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/SolverTools.jl#1]
The amount of required packages is too large.

**Comment by dpo** [comment]
I agree but this package builds on a lot of others. I suppose some of them could be optional.

**Comment by dpo** [comment]
#5 automatically manages the dependencies as a temporary solution.

**Comment by dpo** [comment]
What do you think of the mini build system for unofficial packages? It seems it could be useful to other organization, until packages have settled and are stable enough to be registered. Should it be extracted into a separate package?

**Comment by abelsiqueira** [comment]
Do you mean proposing #5 for the community?

**Comment by dpo** [comment]
Essentially, yes, though I slightly improved it today. It's rudimentary but for a given organization, I'm finding it quite useful.

**Comment by abelsiqueira** [comment]
I think it is a good idea, specially if it could accept more than one unofficial organization. But even if it doesn't, it's still very helpful.

**Comment by abelsiqueira** [comment]
Not a problem anymore after splitting the packages
