### ISSUE TITLE
```counter``` field as a ```NLPModels.Counters```

### ISSUE THREAD

**Issue by PEPERSO** [JuliaSmoothOptimizers/SolverTools.jl#101]
Hello, is it possible to consider the ```counter``` field as a ```NLPModels.Counters``` instead of a ```NLSModels.Counters``` ?

**Comment by abelsiqueira** [comment]
I think you mean `NLPModels.NLSCounters`, and I'm assuming you're talking about `GenericExecutionStats`. Please, correct me if I'm wrong.

Unfortunately, currently, it needs to be an `NLSCounters`, but the creation of a `GenericExecutionStats` is made from either an `NLPModel` or `NLSModel`, and the constructor should work accordingly.

Perhaps is easier to workaround depending on what you're trying to do.

**Comment by PEPERSO** [comment]
Yes, you're absolutely right, my mistake. 
It's just that I would like to use some ```counters.neval_obj``` or ```counters.neval_cons``` fields, but an ```NLSCounters``` has no such field, so I thought a ```NLPModels.Counters``` would be more generic

**Comment by abelsiqueira** [comment]
Are these counters part of an `NLPModel`? If so, you can use `neval_obj(nlp)`.
Although it could be useful to have `neval_obj(counter)` for different counter types.

If you always have an `NLSCOunters`, though, you can use `counter.counters.neval_obj`.

**Comment by PEPERSO** [comment]
Okay that's perfect with ```counter.counters.neval_obj```, thank you
