### ISSUE TITLE
Add empty values in logs

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/SolverTools.jl#151]
Is it possible to insert empty values in `log_row` ?

The aim is that the empty entry would still be aligned with the other columns.
This is useful, for instance, when printing logs for an algorithm that computes two different steps.

**Comment by abelsiqueira** [comment]
Not currently. There is no stored information about columns. I was looking into creating a logger structure to do this.

**Comment by tmigot** [comment]
Would it be simpler if the user gives a Val{Float64} instead of an empty Float64? Then, the function `row_formatter` could put the right number of spaces.

**Comment by abelsiqueira** [comment]
It's worth a try. I'm finishing a draft of the logger structure, so we can compare approaches.
