### ISSUE TITLE
Should TRON max_radius limit the maximum radius every turn?

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/SolverTools.jl#185]
Relevant discussion: https://discourse.julialang.org/t/trust-region-constrained-optimization/93077/6

**Comment by tmigot** [comment]
That's a good question, actually it used in the initialization
https://github.com/JuliaSmoothOptimizers/SolverTools.jl/blob/96b16a4b500dd15176ab766ca42c5f9fca5f3542/src/trust-region/tron-trust-region.jl#L31
but also in the `update!`
https://github.com/JuliaSmoothOptimizers/SolverTools.jl/blob/96b16a4b500dd15176ab766ca42c5f9fca5f3542/src/trust-region/tron-trust-region.jl#L85
However, it is not used in this case where the radius increases:
https://github.com/JuliaSmoothOptimizers/SolverTools.jl/blob/96b16a4b500dd15176ab766ca42c5f9fca5f3542/src/trust-region/tron-trust-region.jl#L83

It is used in the basic `TrustRegion`, so it should be added. We also miss more explicit docstrings for these functions.

**Comment by abelsiqueira** [comment]
I tend to agree with you. Maybe it's an oversight in the definition in the paper, or we copied it wrongly. Either way, I think it is valid to use it in `update!` always.

> We also miss more explicit docstrings for these functions.

Yes. Unfortunately, SolverTools is in the lower layers of our investment, so it usually gets less attention.
