### ISSUE TITLE
Move `compute_As_slope_qs!` in this package

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/SolverTools.jl#196]
https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/blob/5c5294cc90036d606d6aa204d43f03654e61f3e5/src/tronls.jl#L8

This is the same as https://github.com/JuliaSmoothOptimizers/SolverTools.jl/blob/72c5ce136377b6b2c0dab043ee6a2a74379800e9/src/auxiliary/bounds.jl#L93 but used in NLS solvers.

**Comment by Jay-sanjay** [comment]
Hi sir, as far as I see you want to move this function to SolverTools.jl package
https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/blob/5c5294cc90036d606d6aa204d43f03654e61f3e5/src/tronls.jl#L12C1-L23C1

Sir , could move assist me in solving this issue , I would be happy to contribute

**Comment by tmigot** [comment]
Hi @Jay-sanjay ! Thank you for showing a great motivation, and sorry for the delays (I noticed you answered to other issues as well and I am trying to catch-up).

Feel free to open a pull request to fix it and ask reviews from me and maybe @amontoison . Please pay attention to adding unit tests and doc, thank you.

After adding the function in SolverTools.jl,  we will make a new release and remove them from JSSolvers.jl.

**Comment by Jay-sanjay** [comment]
@tmigot  sir I see that `compute_As_slope_qs!` and `compute_Hs_slope_qs!` has exactly same code with just some minor variable name change so, then why is there a need to add it again to SolverTools.jl  ?
Please do correct me if I am wrong

**Comment by amontoison** [comment]
@Jay-sanjay Don't hesitate to ping me for a review.

**Comment by Jay-sanjay** [comment]
@amontoison sir please correct  if I am wrong, both `compute_As_slope_qs!` and `compute_Hs_slope_qs!` functions would function exactly the same way and would give same outputs if same inputs are provided

**Comment by amontoison** [comment]
@Jay-sanjay No, you use the same arguments in both functions, you will have different outputs.
```julia
function compute_As_slope_qs!(
  Hs::AbstractVector{T},                                                      # As
  H::Union{AbstractMatrix, AbstractLinearOperator},  # A
  s::AbstractVector{T},
  g::AbstractVector{T},  # Fx
) where {T <: Real}
  mul!(Hs, H, s)
  slope = dot(Hs, g)
  qs = dot(Hs, Hs) / 2 + slope
  return slope, qs
end

function compute_Hs_slope_qs!(
  Hs::AbstractVector{T},
  H::Union{AbstractMatrix, AbstractLinearOperator},
  s::AbstractVector{T},
  g::AbstractVector{T},
) where {T <: Real}
  mul!(Hs, H, s)
  slope = dot(g, s)
  qs = dot(s, Hs) / 2 + slope
  return slope, qs
end
```

**Comment by Jay-sanjay** [comment]
@amontoison  Here is the PR https://github.com/JuliaSmoothOptimizers/SolverTools.jl/pull/204 , you can review it

**Comment by Jay-sanjay** [comment]
> Hi @Jay-sanjay ! Thank you for showing a great motivation, and sorry for the delays (I noticed you answered to other issues as well and I am trying to catch-up).
> 
> Feel free to open a pull request to fix it and ask reviews from me and maybe @amontoison . Please pay attention to adding unit tests and doc, thank you.
> 
> After adding the function in SolverTools.jl, we will make a new release and remove them from JSSolvers.jl.

 Sir can I work on removing the same from JSSolvers.jl

**Comment by tmigot** [comment]
Hey @Jay-sanjay , Thank you for your contribution. There has been a new release of SolverTools.jl (v0.8.6), so you should be able to remove the function from JSOSolvers now.

**Comment by Jay-sanjay** [comment]
Hello sir I was working on removing the `compute_As_slope_qs` function. But , I see that it is used in various other functions here 
https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/blob/5c5294cc90036d606d6aa204d43f03654e61f3e5/src/tronls.jl#L416C1-L433C1
so what to replace over there....?

**Comment by amontoison** [comment]
`compute_As_slope_qs!` is implemented here so you can remove it from JSOSolvers.jl because SolverTools.jl is a dependency of JSOSolvers.jl.
If the function is exported here it should work fine.
