### ISSUE TITLE
Solvers output

### ISSUE THREAD

**Issue by vepiteski** [JuliaSmoothOptimizers/SolverTools.jl#30]
Distinguish failures from 
- unsuitable models (for instance with constraints for an unconstrained solver) 
- erroneous models (for instance, f(x_0) fails)
- etc. 

More generally, devise a sound output format including the solution, statistics of computation, status (property of the returned solution).

**Comment by abelsiqueira** [comment]
The `ExecutionStats` [here](https://github.com/JuliaSmoothOptimizers/SolverTools.jl/blob/master/src/stats/stats.jl) should be it, but it doesn't handle every possible case. Also see #90.

**Comment by tmigot** [comment]
Outdated
