### ISSUE TITLE
Better output for GenericExecutionStats

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/SolverTools.jl#93]
Something like
```
Execution stats:
 - Status: ...
 - Dual measure: ...
 - Primal measure: ...
```

**Comment by Jay-sanjay** [comment]
Hello sir , I would be happy to work on this issue 
Correct me if I am wrong here you want me to add a custom show method for better output formatting
https://github.com/JuliaSmoothOptimizers/SolverTools.jl/blob/b2bbf681daba13eb1772181f4e11cf9d152e3c9c/test/dummy_solver.jl#L64C1-L77C1

Could you please assist me for it

**Comment by abelsiqueira** [comment]
Hi @Jay-sanjay, sorry, I missed this comment. This issue should be in https://github.com/JuliaSmoothOptimizers/SolverCore.jl/issues/80 now. I am closing this.
